'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import { CalendarPlus, ExternalLink, MapPin, Trophy } from 'lucide-react';
import type { ParticipantAccessMatch, ParticipantAccessPayload } from '@bracket/shared';
import { Button } from '@/components/ui/button';
import { api, API_URL } from '@/lib/api';

/**
 * Mobile-first personal page for a participant, reached from a QR code or
 * access link handed out by the organizer (`/p/:token`).
 */
export default function ParticipantAccessPage() {
  const { token } = useParams<{ token: string }>();
  const qc = useQueryClient();
  const { data, isLoading, error } = useQuery({
    queryKey: ['participant-access', token],
    queryFn: () => api<ParticipantAccessPayload>(`/p/${token}`),
    refetchInterval: 30_000,
  });

  return (
    <div className="min-h-screen bg-[var(--color-bg,#0a0c10)]">
      <main className="mx-auto max-w-md px-4 pb-16 pt-6">
        {isLoading && <p className="text-sm text-[var(--color-muted)]">Loading your schedule…</p>}
        {error && (
          <div className="gaming-card rounded-2xl p-6 text-center">
            <p className="font-semibold">Link not valid</p>
            <p className="mt-1 text-sm text-[var(--color-muted)]">
              {error instanceof Error
                ? error.message
                : 'This access link is invalid or was regenerated by the organizer.'}
            </p>
          </div>
        )}
        {data && (
          <>
            <header className="mb-5 flex items-center gap-3">
              {data.tournament.logoUrl && (
                <img src={data.tournament.logoUrl} alt="" className="h-12 w-12 rounded-xl object-cover" />
              )}
              <div className="min-w-0">
                <p className="truncate text-xs uppercase tracking-wide text-[var(--color-muted)]">
                  {data.tournament.name}
                </p>
                <h1 className="font-display truncate text-2xl font-bold">{data.team.name}</h1>
                <p className="text-xs text-[var(--color-muted)]">
                  {data.team.seed ? `Seed ${data.team.seed} · ` : ''}
                  {data.record.wins}W–{data.record.losses}L
                  {data.record.draws ? `–${data.record.draws}D` : ''}
                  {data.actions.checkedIn ? ' · Checked in' : ''}
                </p>
              </div>
            </header>

            <WhatNowCard
              data={data}
              token={token}
              onChanged={() => void qc.invalidateQueries({ queryKey: ['participant-access', token] })}
            />

            <div className="mt-4 grid grid-cols-2 gap-2">
              <a
                href={`${API_URL}/p/${token}/schedule.ics`}
                className="flex items-center justify-center gap-1.5 rounded-xl border border-[var(--color-line)] px-3 py-2.5 text-xs font-semibold"
              >
                <CalendarPlus className="h-4 w-4" /> Add to calendar
              </a>
              <Link
                href={`/t/${data.tournament.slug}`}
                className="flex items-center justify-center gap-1.5 rounded-xl border border-[var(--color-line)] px-3 py-2.5 text-xs font-semibold"
              >
                <ExternalLink className="h-4 w-4" /> Tournament page
              </Link>
            </div>

            {data.standing && (
              <section className="gaming-card mt-5 rounded-2xl p-4">
                <p className="mb-2 flex items-center gap-1.5 text-xs uppercase tracking-wide text-[var(--color-muted)]">
                  <Trophy className="h-3.5 w-3.5" /> Standing
                  {data.standing.groupName ? ` · ${data.standing.groupName}` : ''}
                </p>
                <div className="flex items-end justify-between">
                  <p className="font-display text-4xl font-bold">
                    {data.standing.rank}
                    <span className="text-base font-normal text-[var(--color-muted)]">
                      {' '}
                      / {data.standing.groupSize}
                    </span>
                  </p>
                  <dl className="grid grid-cols-4 gap-3 text-center text-xs">
                    <Stat label="P" value={data.standing.played} />
                    <Stat label="W" value={data.standing.wins} />
                    <Stat label="L" value={data.standing.losses} />
                    <Stat label="Pts" value={data.standing.points} accent />
                  </dl>
                </div>
              </section>
            )}

            <section className="mt-5">
              <p className="mb-2 text-xs uppercase tracking-wide text-[var(--color-muted)]">All matches</p>
              {data.matches.length === 0 ? (
                <p className="rounded-xl border border-dashed border-[var(--color-line)] p-4 text-center text-sm text-[var(--color-muted)]">
                  Your matches will show up here once the bracket is generated.
                </p>
              ) : (
                <ul className="space-y-2">
                  {data.matches.map((m) => (
                    <MatchRow key={m.id} m={m} />
                  ))}
                </ul>
              )}
            </section>

            {data.team.players.length > 0 && (
              <section className="mt-5 text-xs text-[var(--color-muted)]">
                <p className="mb-1 uppercase tracking-wide">Roster</p>
                <p>{data.team.players.join(' · ')}</p>
              </section>
            )}
          </>
        )}
      </main>
    </div>
  );
}

function Stat({ label, value, accent }: { label: string; value: number; accent?: boolean }) {
  return (
    <div>
      <dt className="text-[var(--color-muted)]">{label}</dt>
      <dd className={`font-mono text-base font-semibold ${accent ? 'text-[var(--color-accent)]' : ''}`}>
        {value}
      </dd>
    </div>
  );
}

function fmtTime(iso: string | null) {
  if (!iso) return null;
  const d = new Date(iso);
  const today = new Date();
  const sameDay = d.toDateString() === today.toDateString();
  return sameDay
    ? `Today ${d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`
    : d.toLocaleString([], {
        weekday: 'short',
        month: 'short',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      });
}

function WhatNowCard({
  data,
  token,
  onChanged,
}: {
  data: ParticipantAccessPayload;
  token: string;
  onChanged: () => void;
}) {
  const match = data.nextMatch;
  const { actions } = data;

  const checkIn = useMutation({
    mutationFn: () => api(`/p/${token}/check-in`, { method: 'POST' }),
    onSuccess: () => {
      toast.success('You are checked in');
      onChanged();
    },
    onError: (err: Error) => toast.error(err.message),
  });

  let title = 'What you do now';
  let body = 'No upcoming match right now — check back soon.';
  if (data.tournament.status === 'COMPLETED') {
    title = 'Tournament complete';
    body = 'Thanks for playing.';
  } else if (data.tournament.status === 'DRAFT') {
    body = 'Waiting for the organizer to start the tournament.';
  } else if (actions.canCheckIn) {
    title = 'Check in';
    body = 'The organizer needs you checked in before results can be entered.';
  } else if (match) {
    title = `Next: vs ${match.opponent?.name ?? 'TBD'}`;
    body = match.roundLabel;
  }

  return (
    <div className="gaming-card rounded-2xl p-5">
      <p className="text-xs uppercase tracking-wide text-[var(--color-accent)]">{title}</p>
      {match && data.tournament.status !== 'COMPLETED' ? (
        <>
          <p className="font-display mt-2 text-3xl font-bold leading-tight">
            vs {match.opponent?.name ?? 'TBD'}
          </p>
          <div className="mt-3 flex flex-wrap gap-3 text-sm">
            <span className="rounded-lg bg-[var(--color-surface)] px-3 py-1.5 font-semibold">
              {fmtTime(match.scheduledAt) ?? (match.status === 'READY' ? 'Ready to play' : 'Time TBA')}
            </span>
            {match.station && (
              <span className="flex items-center gap-1 rounded-lg bg-[var(--color-surface)] px-3 py-1.5">
                <MapPin className="h-3.5 w-3.5" /> {match.station}
              </span>
            )}
          </div>
        </>
      ) : (
        <p className="mt-2 text-sm text-[var(--color-muted)]">{body}</p>
      )}

      {actions.canCheckIn && (
        <Button
          className="mt-4 w-full"
          disabled={checkIn.isPending}
          onClick={() => checkIn.mutate()}
        >
          {checkIn.isPending ? 'Checking in…' : 'Check in now'}
        </Button>
      )}

      {actions.canReportScore && match && (
        <ScoreForm token={token} match={match} teamId={data.team.id} onSaved={onChanged} />
      )}
    </div>
  );
}

function ScoreForm({
  token,
  match,
  teamId,
  onSaved,
}: {
  token: string;
  match: ParticipantAccessMatch;
  teamId: string;
  onSaved: () => void;
}) {
  const [open, setOpen] = useState(false);
  const [mine, setMine] = useState('');
  const [theirs, setTheirs] = useState('');
  const myN = Number(mine);
  const theirN = Number(theirs);
  const valid = mine !== '' && theirs !== '' && !Number.isNaN(myN) && !Number.isNaN(theirN) && myN >= 0 && theirN >= 0;
  const homeScore = match.isHome ? myN : theirN;
  const awayScore = match.isHome ? theirN : myN;
  const winnerTeamId =
    !valid || myN === theirN ? null : myN > theirN ? teamId : (match.opponent?.id ?? null);

  const save = useMutation({
    mutationFn: () =>
      api(`/p/${token}/matches/${match.id}/result`, {
        method: 'PATCH',
        body: JSON.stringify({
          homeScore,
          awayScore,
          isDraw: myN === theirN,
          winnerTeamId: winnerTeamId ?? null,
        }),
      }),
    onSuccess: () => {
      toast.success('Result submitted');
      setOpen(false);
      onSaved();
    },
    onError: (err: Error) => toast.error(err.message),
  });

  if (!open) {
    return (
      <Button className="mt-4 w-full" type="button" onClick={() => setOpen(true)}>
        Report score
      </Button>
    );
  }

  return (
    <div className="mt-4 space-y-3">
      <div className="grid grid-cols-2 gap-3">
        <label className="text-xs">
          <span className="mb-1 block text-[var(--color-muted)]">You</span>
          <input
            type="number"
            inputMode="numeric"
            min={0}
            value={mine}
            onChange={(e) => setMine(e.target.value)}
            className="h-11 w-full rounded-lg border border-[var(--color-line)] bg-[var(--color-surface)] text-center font-mono text-lg"
          />
        </label>
        <label className="text-xs">
          <span className="mb-1 block text-[var(--color-muted)]">{match.opponent?.name ?? 'Opponent'}</span>
          <input
            type="number"
            inputMode="numeric"
            min={0}
            value={theirs}
            onChange={(e) => setTheirs(e.target.value)}
            className="h-11 w-full rounded-lg border border-[var(--color-line)] bg-[var(--color-surface)] text-center font-mono text-lg"
          />
        </label>
      </div>
      <div className="grid grid-cols-2 gap-2">
        <Button type="button" variant="secondary" onClick={() => setOpen(false)}>
          Cancel
        </Button>
        <Button type="button" disabled={!valid || save.isPending} onClick={() => save.mutate()}>
          {save.isPending ? 'Saving…' : 'Submit'}
        </Button>
      </div>
    </div>
  );
}

function MatchRow({ m }: { m: ParticipantAccessMatch }) {
  const done = m.status === 'COMPLETED';
  const tone =
    m.result === 'win'
      ? 'text-emerald-500'
      : m.result === 'loss'
        ? 'text-red-500'
        : m.result === 'draw'
          ? 'text-amber-500'
          : 'text-[var(--color-muted)]';
  return (
    <li className="flex items-center gap-3 rounded-xl border border-[var(--color-line)] bg-[var(--color-card)] px-3 py-2.5 text-sm">
      <span className={`w-9 shrink-0 text-center font-mono text-xs font-bold uppercase ${tone}`}>
        {done ? (m.result === 'win' ? 'W' : m.result === 'loss' ? 'L' : 'D') : '·'}
      </span>
      <span className="min-w-0 flex-1">
        <span className="block truncate font-medium">vs {m.opponent?.name ?? 'TBD'}</span>
        <span className="block truncate text-[11px] text-[var(--color-muted)]">
          {m.roundLabel}
          {m.station ? ` · ${m.station}` : ''}
          {!done && m.scheduledAt ? ` · ${fmtTime(m.scheduledAt)}` : ''}
        </span>
      </span>
      <span className="shrink-0 font-mono font-semibold">
        {done ? `${m.myScore ?? 0}–${m.opponentScore ?? 0}` : ''}
      </span>
    </li>
  );
}
