ALTER TYPE "MatchStatus" ADD VALUE IF NOT EXISTS 'IN_PROGRESS';

ALTER TABLE "Tournament" ADD COLUMN IF NOT EXISTS "circuitSeason" TEXT;
ALTER TABLE "Tournament" ADD COLUMN IF NOT EXISTS "circuitRegion" TEXT;
ALTER TABLE "Tournament" ADD COLUMN IF NOT EXISTS "circuitTier" TEXT;

ALTER TABLE "Standing" ADD COLUMN IF NOT EXISTS "homeWins" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Standing" ADD COLUMN IF NOT EXISTS "homeDraws" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Standing" ADD COLUMN IF NOT EXISTS "homeLosses" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Standing" ADD COLUMN IF NOT EXISTS "awayWins" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Standing" ADD COLUMN IF NOT EXISTS "awayDraws" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Standing" ADD COLUMN IF NOT EXISTS "awayLosses" INTEGER NOT NULL DEFAULT 0;
