ALTER TYPE "MatchStatus" ADD VALUE IF NOT EXISTS 'PROVISIONAL';

ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "homeArrivedAt" TIMESTAMP(3);
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "awayArrivedAt" TIMESTAMP(3);
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "reviewStatus" TEXT;
ALTER TABLE "Match" ADD COLUMN IF NOT EXISTS "reviewNote" TEXT;
